// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "@prisma/config";

export default defineConfig({
  // 💡 Explicitly point Prisma to your custom schema path
  schema: "src/prisma/schema.prisma",

  migrations: {
    path: "src/prisma/migrations",
  },

  datasource: {
    url: env('DATABASE_URL'),
  },
});
